### ISSUE TITLE
No Fullscreen on IOS

### ISSUE THREAD

**Issue by railnation** [GradleFx/GradleFx-Documentation#8]
Hi, 

I have a problem using gradleFX on IOS deployment. My app does not run in fullscreen mode on IOS, can you tell me why? If I use a deploy from FDT the app runs in fullscreen mode.

Best regards

**Comment by SlevinBE** [comment]
Do you have the following in your air application descriptor file?

`<fullscreen>true</fullscreen>`

**Comment by SlevinBE** [comment]
Also, make sure you've set the UIDeviceFamily correctly to indicate that your app supports iPhone/iPad: http://help.adobe.com/en_US/air/build/WSfffb011ac560372f7e64a7f12cd2dd1867-8000.html#WS901d38e593cd1bac-3cb3c27712e2339d6cd-8000

**Comment by railnation** [comment]
Hi, 

I have this for device familiy 

<key>UIDeviceFamily</key>
  <array>
    <string>1</string>
    <string>2</string>
  </array>

and yes fullscreen set to true

**Comment by SlevinBE** [comment]
This might also be related to launch images not being included when building with Gradle, while they might get picked up by FDT when they are located in the root src folder of your project.

You can specify these to the ADT package compiler in GradleFx like this (depending on the launch images your use):

```
air {
  fileOptions = [
    'Default-568h@2x~iphone.png',
    'Default-375w-667h@2x~iphone.png',
    'Default-414w-736h@3x~iphone.png'
  ]
}
```

**Comment by SlevinBE** [comment]
Note: the launch image affecting the fullscreen behaviour of iOS apps isn't Gradle specific, it's something apparently affecting all kinds of iOS apps (eg: [https://forums.xamarin.com/discussion/19917/ios-app-not-displaying-in-full-screen](https://forums.xamarin.com/discussion/19917/ios-app-not-displaying-in-full-screen))

**Comment by railnation** [comment]
Thanks, I forgot to add the default ios splash images
